### ISSUE TITLE
Absence of openpyxl library causes console errors

### ISSUE THREAD

**Issue by l0uden** [mckinsey/vizro#86]
### Description

When trying to export xlsx file using actions, console error occurs

```
Traceback (most recent call last):
  File "/Users/o/PycharmProjects/vizro/vizro-core/src/vizro/models/_action/_action.py", line 80, in callback_wrapper
    return_value = self.function(**inputs) or {}
  File "/Users/o/PycharmProjects/vizro/vizro-core/src/vizro/models/types.py", line 59, in __call__
    return self.__function(**bound_arguments.arguments)
  File "/Users/o/PycharmProjects/vizro/vizro-core/src/vizro/actions/export_data_action.py", line 61, in export_data
    callback_outputs[f"download-dataframe_{target_id}"] = dcc.send_data_frame(
  File "/Users/o/anaconda3/envs/w3af/lib/python3.8/site-packages/dash/dcc/express.py", line 91, in send_data_frame
    return _data_frame_senders[name](writer, filename, type, **kwargs)
  File "/Users/o/anaconda3/envs/w3af/lib/python3.8/site-packages/dash/dcc/express.py", line 32, in send_bytes
    content = src if isinstance(src, bytes) else _io_to_str(io.BytesIO(), src, **kwargs)
  File "/Users/o/anaconda3/envs/w3af/lib/python3.8/site-packages/dash/dcc/express.py", line 58, in _io_to_str
    writer(data_io, **kwargs)
  File "/Users/o/anaconda3/envs/w3af/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/Users/o/anaconda3/envs/w3af/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/Users/o/anaconda3/envs/w3af/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
```

### vizro version

0.1.3

### Python version

3.8

### OS

Mac OS

### How to Reproduce

1. Install vizro package into clean env
2. Add export xlsx action to the dashboard
3. Run export action

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
I would probably classify this as "Don't fix":
* I don't see any good way to fix it...
* I suspect it doesn't affect many people (but would be good to find out)
* [validation decorator](https://docs.pydantic.dev/latest/concepts/validation_decorator/) _might_ provide a better way to check for dependencies upfront with pydantic v2.

Instead I'd suggest just adding a note to the documentation that if you specify `file_format="xlsx"` then you need to have `openpyxl` or `xlsxwriter` installed (I don't know how pandas chooses between these two when no `engine` is specified in `to_excel` - we'd need to check).
